### ISSUE TITLE
MultiPolygon Handling

### ISSUE THREAD

**Issue by deckar01** [stmcculloch/arc-overhang#1]
```
  ...
  File "arc-overhang/util.py", line 183, in create_arc
    if not coord in remaining_empty_space.exterior.coords:
AttributeError: 'MultiPolygon' object has no attribute 'exterior'
```

```
  ...
  File "arc-overhang/util.py", line 182, in create_arc
    for coord in crescent.exterior.coords:
AttributeError: 'MultiPolygon' object has no attribute 'exterior'
```

**Comment by deckar01** [comment]
https://github.com/deckar01/arc-overhang/commit/eb620ab6b44e4bb77d53b0a0432db68602bc1be7

**Comment by stmcculloch** [comment]
Yeah this issue is a bit tricky. I don't think multipolygons should even exist in the first place, so handling them might end up causing more errors than finding the root cause of their existence. 

This seems to occur more frequently when N is low. Try setting N to 7 (to make hexagons instead of arcs) and you'll get some kind of error every time.
